name: CI-CD-ANDROID_APK
on:
  push:
    branches: [master]  
    
env:
  flutter_channel: 'stable'
  flutter_version: '2.8.1'
 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
            
      - uses: actions/setup-java@v1
        with:
          java-version: "1.8"
          
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.8.1'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter format .
      - run: flutter build apk --debug --split-per-abi
      - uses: ncipollo/release-action@v1
        with:
          name: release-apks
          artifacts: "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"
          tag:  v1.0.${{ github.run_number }}
          token: ${{ secrets.GIT_TOKEN}}
          
          
